name: APOC-End-Reset
main: org.apocgaming.endreset.EndResetPlugin
version: 1.3
authors: [Zilacon, Capsar, FreakyFalse, Ratismal]
description: A bukkit minecraft plugin that automatically resets the end when the dragon is killed and distributes the rewards.

commands:
   endreset:
      description: Main command, shows all other available commands.
      usage: /<command>
      permission: endreset.admin
      permission-message: You don't have <permission>