# Apocalyptic Gaming Network END Reset Plugin
# Programmed By: Capsar, FreakyFalse of the APOC Gaming Dev Team
# Idea & Config By: Zilacon
#
# For any questions about our plugin feel free to contact us at http://apocgaming.org
# For issues with our plugin please make a issue ticket on our github at https://github.com/Zilacon/APOC-End-Reset/issues
#
# Below is the configurable options for the plugin. You can set the total experience for the dragon.
# The distribution of the rewards. The delay of the end resetting. Locking down the end.
# And where the players will be teleported when the dragon is killed.
#
# This plugin regenerates the world with the same seed it was created with.
# So as long as the level.dat file is intact for the world the seed will remain unchanged.
# This makes it easy to setup warps to the end as the platform for the end will never change.

# end-reward:
# This is the TOTAL experience that will be distributed between all players that killed the dragon. (22075 = 100 levels)
total-exp: 22075
# Do you want the player who killed the dragon to get the dragon egg?
reward-egg: true

# end-teleport:
# Where should we teleport the players after we close the end?
# Choose the name of the world and the coordinates X,Y,Z to where they will spawn at.
end-tp-world: Spawn
end-tp-coord: 0,25,0
# The time the players have left in the end after killing the dragon before they get teleported to the given coordinates above. (In minutes)
end-tp-out-delay: 10

# end-reset:
# How long until the world is reset in minutes? (After the dragon is killed)
end-reset-time: 30
# Should we lock down the world until the end has reset after the players got teleported out? This prevents players from entering the end again.
end-lockdown: true