name: APOC-End-Reset
main: org.apocgaming.endreset.EndReset
version: 1.1
authors: [Zilacon, Capsar, FreakyFalse]
description: A bukkit minecraft plugin that automatically resets the end when the dragon is killed and distributes the rewards.

commands:
   apocer:
      description: Main command, shows all other available commands.
      usage: /<command>
      permission: endreset.admin
      permission-message: You don't have <permission>